server:
  port: 9081
  tomcat:
    threads:
      max: 10 # 最大线程数
spring:
  application:
    name: lego-learn-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/zeus?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  # m1芯片 docker run --name nacosAtHome01 -e MODE=standalone -p 8848:8848 -p 9848:9848 -d zhusaidong/nacos-server-m1:2.0.3
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#    openfeign:
#      client:
#        config:
#          lego-finance-server:   # 可以配置default或者对单独服务生效
#            connectTimeout: 500  # 连接超时时间
#            readTimeout: 500     # 读取超时时间
    sentinel:
      transport:
        dashboard: localhost:7070
        port: 8719
