server:
  port: 8081
  tomcat:
    threads:
      max: 10 # 最大线程数
spring:
  application:
    name: lego-finance-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lego_finance?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  # m1芯片 docker run --name nacosAtHome01 -e MODE=standalone -p 8848:8848 -p 9848:9848 -d zhusaidong/nacos-server-m1:2.0.3
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:7070
        port: 8719
